const REQUEST_CHAPTERS = 'REQUEST_CHAPTERS'
const RECEIVE_CHAPTERS = 'RECEIVE_CHAPTERS'
const CHAPTER_ADDED = 'CHAPTER_ADDED'
const CHAPTER_DELETED = 'CHAPTER_DELETED'

export {
    REQUEST_CHAPTERS,
    RECEIVE_CHAPTERS,
    CHAPTER_ADDED,
    CHAPTER_DELETED
}