const REQUEST_BOOKS = 'REQUEST_BOOKS'
const RECEIVE_BOOKS = 'RECEIVE_BOOKS'
const BOOK_ADDED = 'BOOK_ADDED'
const BOOK_DELETED = 'BOOK_DELETED'
const CLEAR_BOOKS = 'CLEAR_BOOKS'

export {
  REQUEST_BOOKS,
  RECEIVE_BOOKS,
  BOOK_ADDED,
  BOOK_DELETED,
  CLEAR_BOOKS
}
