const REQUEST_BOOK_TO_EDIT = 'REQUEST_BOOK_TO_EDIT'
const RECEIVE_BOOK_TO_EDIT = 'RECEIVE_BOOK_TO_EDIT'
const BOOK_EDIT_START = 'BOOK_EDIT_START'
const BOOK_EDIT_END = 'BOOK_EDIT_END'

export {
  REQUEST_BOOK_TO_EDIT,
  RECEIVE_BOOK_TO_EDIT,
  BOOK_EDIT_START,
  BOOK_EDIT_END
}
