const NOTIFICATIONS_ADD = 'NOTIFICATIONS_ADD'
const NOTIFICATIONS_REMOVE = 'NOTIFICATIONS_REMOVE'
const NOTIFICATIONS_CLEAR = 'NOTIFICATIONS_CLEAR'

export {
  NOTIFICATIONS_ADD,
  NOTIFICATIONS_REMOVE,
  NOTIFICATIONS_CLEAR
}
