const REGISTER_START = 'REGISTER_START'
const REGISTER_READY = 'REGISTER_READY'
const LOGIN_START = 'LOGIN_START'
const LOGIN_READY = 'LOGIN_READY'
const LOGIN_USER_DATA_RECEIVED = 'LOGIN_USER_DATA_RECEIVED'
const LOGOUT_START = 'LOGOUT_START'
const LOGOUT_END = 'LOGOUT_END'

export {
  REGISTER_START,
  REGISTER_READY,
  LOGIN_START,
  LOGIN_READY,
  LOGIN_USER_DATA_RECEIVED,
  LOGOUT_START,
  LOGOUT_END
}
