const REGISTER_START = 'REGISTER_START'
const REGISTER_READY = 'REGISTER_READY'
const LOGIN_START = 'LOGIN_START'
const LOGIN_READY = 'LOGIN_READY'

export {
  REGISTER_START,
  REGISTER_READY,
  LOGIN_START,
  LOGIN_READY
}
